### PR TITLE
Fix a couple of typos in readme

### PR DESCRIPTION
**Pull request by g40**
Hi Yuji, some readme tweaks.

### CODE REVIEW

**Comment by yhirose** [comment]
Thanks for finding the mistakes! How embracing...

**Comment by g40** [comment]
Another typo? Apologies in advance if I have made language assumptions :)

embracing : 受け入れ
embarrassing: 厄介な

**Comment by yhirose** [comment]
Oops... How truly embarrassing. English is much more difficult to learn than C++.

**Comment by g40** [comment]
You seem to be doing very well with both. 乾杯

**Pull request merged**
