### PR TITLE
Enhancements

### PR DESCRIPTION
**Pull request by mumme74**
Hi!

I made some changes to yout project. 

- Print syntax errors in a more nice way

- Made tracing more usefull

- Added a traceback functionallity

- Som bugfixes where it got stuck in an endless loop

Please consider merging!

### CODE REVIEW

**Comment by yhirose** [comment]
@mumme74, thanks for the pull request. I took a quick glance at it, but it's too big to me to review it... Since I simply don't have time to review all of the changes at once, could you split it to individual pull requests per feature or bug. It will be much easer for me to review. Thanks for your consideration.

**Comment by mumme74** [comment]
Ok, I have spent some time this weekend to split into parts and made pull requests for each of them.
I can't split all parts so they are based of current master. Some changes depend on changes in these pull requests.
Please review the 4 pull requests I made first.

**Comment by yhirose** [comment]
@mumme74, thanks for your efforts to split it.

I took a glance at the pull requests, but they are still pretty big to me. I guess it will take time to handle each pull request.

Also as you can see other issues or pull requests in this project or other my project like cpp-httplib, I usually don't merge pull requests directly as they are unless they are very small changes or I fully understand what they are doing. Sometimes, I just get ideas from pull requests from users and implement in a totally different way.

I am much more interested in bugs than extra features. So I'll probably take a look at #76 first.

Thanks for your contribution and consideration!

**Comment by yhirose** [comment]
Please see my comments in respective pull requests. Thank you!

**Pull request closed without merging**
