### PR TITLE
suggestion for a whitespace handling rule

### PR DESCRIPTION
**Pull request by g40**
Hi Yuji, 

This is just an idea about how to add automatic whitespace lexing. The idea is to pass a whitespace rule to each of the parse functions. The default implementation does nothing and is passed by default to parse_core. In this experiment I've derived WsRule from Ope so it can reuse all of the grammar rule parsing and mapping functionality. The idea would be to call parse() on the WsRule instance on entry to, and on exit from, each terminal. Thus whitespace would be consumed as it would be by default in Lex/Antlr/CoCo etc. Please let me know what you think.

BR, Jerry.

BTW apologies for the large diff. My formatting is messing things up. 
```
virtual size_t parse(const char* s, size_t n, SemanticValues& sv, Context& c, any& dt, WsRule& wsr) const = 0;
```

The change to the top-level entry would then be something like this:
```
	bool parse_n(const char* s, size_t n, const char* path = nullptr) const {
		if (grammar_ != nullptr) {
			const auto& rule = (*grammar_)[start_];
			// null implementation
			WsRule& wsr = WsRule();
			// check to see if grammar defined custom whitespace rule ...
			if (grammar_->find("WS") != grammar_->end())
			{
				// ...
			}
			auto r = rule.parse(s, n, path);
			output_log(s, n, log, r);
			return r.ret && r.len == n;
		}
		return false;
	}
```

### CODE REVIEW

**Comment by yhirose** [comment]
Hi Jerry,

Thanks for bringing the matter to my attention. I have actually researched about it before (in fact, there is an item "Ignore white spaces after string literals and tokens" under the [TODO](https://github.com/yhirose/cpp-peglib#todo) section). But I couldn't find a clear solution to support the feature. Here are some popular PEG libraries that I referred to:

* pegjs - https://github.com/pegjs/pegjs/issues/11
* parboiled - https://github.com/sirthias/parboiled/wiki/Handling-Whitespace
* rattler (my favorite solution) - http://www.relishapp.com/jarhart/rattler/docs/extended-matching-syntax/whitespace-skipping and http://www.relishapp.com/jarhart/rattler/docs/extended-matching-syntax/token-operator

As you can see in the above articles, it's quite hard to support it correctly in PEG parser since it doesn't have clear distinction between 'parser' and 'lexer'.

Of course, I understand how useful the feature would be as you feel. So I'll think of a way to implement it based on the above ideas and yours. I made a branch for this purpose named 'whitespace'. Hope you will see something interesting in the near future. (But don't expect too soon since it's my afterwork project. :smile:)

Thanks,
Yuji

**Comment by yhirose** [comment]
Hi Jerry,

I have just implemented the feature in the `whitespace` branch (https://github.com/yhirose/cpp-peglib/compare/whitespace). I borrowed your idea 'Whitespace Rule' and implemented it on the `Context` object instead of adding another parameter on `parse` method, so that the change could be small. I think this idea works pretty well in most situations.

It now supports a new special rule `%whiltespace` which is similar to `WS` in ANTLR. The key of using this feature effectively is to distinguish *tokens* and *rules* clearly.

`%whitespace` rule can be applied to the following three conditions:

* trailing spaces on tokens
* leading spaces on text
* trailing spaces on literal strings in rules

These are valid tokens:

```
KEYWORD  <- 'keyword'
WORD     <-  [a-zA-Z0-9] [a-zA-Z0-9-_]*        # no reference rule is used
IDNET    <-  < IDENT_START_CHAR IDENT_CHAR* >  # token boundary operator is used.
```

Here is the new grammar of [calc3.cc](https://github.com/yhirose/cpp-peglib/blob/whitespace/example/calc3.cc#L43-L51).

```
# Rules
EXPRESSION       <-  TERM (TERM_OPERATOR TERM)* # skip leading spaces on text 
TERM             <-  FACTOR (FACTOR_OPERATOR FACTOR)*
FACTOR           <-  NUMBER / '(' EXPRESSION ')' # skip trailing spaces on '(' and ')'

# Tokens
TERM_OPERATOR    <-  [-+] # skip trailing spaces on the token
FACTOR_OPERATOR  <-  [/*] # skip trailing spaces on the token
NUMBER           <-  [0-9]+ # skip trailing spaces on the token

%whitespace      <-  [ \t\r\n]*
```

The grammar looks much nicer!!

Does this solution make sense to you? Please let me know your thoughts.

Thank you,
Yuji

**Comment by g40** [comment]
Hi Yuji. looks great. Let me try it out on my GDB grammar. Thanks.

**Comment by g40** [comment]
Apologies. Not quite sure how I did that!

**Comment by yhirose** [comment]
The whitespace handling code has been merged into the master branch. Thanks for your help!

**Pull request closed without merging**
