### PR TITLE
Reorganize as modern CMake with an interface target

### PR DESCRIPTION
**Pull request by kfsone**
Cleanup/reorganize the cmake lists files to present peglib as an interface target and default-disable building of linter, examples and test when peglib is not the primary build tree.

- Added a 'CppPegLib' interface target,
- Moved compiler flags from CMAKE_CXX_FLAGS global variable to properties on CppPegLib,
- Moved include paths from the global list to just the CppPegLib,
- Moved linker dependencies (pthreads) to CppPegLib and restricted the search for the library to just Linux too,
- Added options for building the linter and the examples,
- Made options default to 'OFF' when the user isn't building peglib directly (e.g its being vendor'd or fetch-content'd),
- Moved options to cmake/PeglibOptions.cmake,
- Moved other pieces of cmake configuration into cmake/*.cmake to keep the main CMakeLists trim and readable,

The aim here was to make it easier to integrate peglib into other code bases as a header-only library, without it potentially contaminating the compiler flags / linker settings / include paths of other targets/projects.

To use with this new construct, one needs to:

```
add_subdirectory(cpp-peglib)

add_executable(my_executable main.cpp)  # or add_library

target_link_libraries(my_executable CppPegLib)
```

Doing so will inherit the include path, necessary compiler flags, and any linker flags to your target.

If you are building a library that pulls in CppPegLib, you may want to make the inclusion PRIVATE so that the compiler/link flags, include paths, etc do not leak upwards for you.

```
add_library(my-middleware library.cpp grammar.cpp ...)
target_link_libraries(my-middleware PRIVATE CppPegLib)
```

### CODE REVIEW

**Comment by kfsone** [comment]
The appveyor may fail, I'm unfamiliar with appveyor and it's possible that the config needs tweaking to support the changes here.

**Comment by kfsone** [comment]
Ah, you have .cmake files in the .gitignore, fixed.

Do you usually build in-directory rather than into a bin directory?

When I'm command-line hacking, my cmake workflow is usually something like:

```
cd cpp-peglib
cmake -G Ninja -B build .  # write cmake files to ./build/
cmake --build build  # have cmake launch whatever it configured as the compiler;
# add --target <target name> or --config <Release|Debug> to suit.
```

**Comment by yhirose** [comment]
Thanks for the pull request, but I would like to keep the current simple CMakeList.txt as it is, since I am not a CMake expert and I don't have any need to enhance it for now. Thanks for your understanding!

**Comment by kfsone** [comment]
Totally understand, the motivation was that the current implementation modifies CMake globals which can then incorrectly propagate to other targets.

I'll take a shot at a much simpler change separately.

**Pull request closed without merging**
