### PR TITLE
Add cmake toggle to disable tests

### PR DESCRIPTION
**Pull request by NotAPenguin0**
Building tests by default is not necessary, so I added a cmake `option()` command `PEGLIB_BUILD_TESTS` that can be used to toggle this on or off (default value is OFF).

### CODE REVIEW

**Comment by yhirose** [comment]
@NotAPenguin0, thanks for the pull request. Personally, I always want to include the unit testing. Could you please make it `ON` as default, so that I don't have to specify the additional option all the time?

**Comment by NotAPenguin0** [comment]
Added :)

**Comment by yhirose** [comment]
@NotAPenguin0, another question is, is it a common practice used in other open source projects? I have never make unit test optional in any my projects.

**Comment by NotAPenguin0** [comment]
I believe so yeah, the unit tests are mostly for library developers. As a user I prefer not to waste build time compiling and/or running tests. Adding the toggle just adds more flexibility in the end.

**Comment by yhirose** [comment]
Thanks for the answer!

**Pull request merged**
